version: '3.7'

services:
#       Webserver
  imse-app:
    image: kwindsor/php7-apache-ubuntu
    container_name: imse-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./src/php:/var/www/html:rw
#      Database
  mariadb:
    image: mariadb
    restart: always
    stdin_open: true
    tty: true
      #- my-db:/var/lib/mysql:rw
      #- ./mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=imse_db
      - MYSQL_ROOT_PASSWORD=rootpsw
      - MYSQL_USER=imse_user
      - MYSQL_PASSWORD=userpsw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    container_name: mariadb_database
#   Filler
  filler:
    image: mysql
    build:
      context: .
      dockerfile: Filler.dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./mysql:/mysql
