version: '3.7'

services:
#       Webservice
  imse-app:
    image: kwindsor/php7-apache-ubuntu
    build: ./web/
    container_name: imse-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./src/php:/var/www/html:rw
# Database
  mariadb:
    image: mariadb
    build: ./mysql/
    restart: always
    environment: 
      - MYSQL_DATABASE=imse_db
      - MYSQL_ROOT_PASSWORD=rootpsw
      - MYSQL_USER=imse_user
      - MYSQL_PASSWORD=imsepsw
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:rw
    ports:
      - target: 3308
        published: 3308
        protocol: tcp
# Filler 
  filler: 
    image: openjdk:8
    build: ./filler/
    volumes: 
      - ./src/java/:/src/java/filler
    depends_on:
      - mariadb
volumes: 
 my-db:

